apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerebral-api-deployment
  namespace: cerebral
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cerebral-api
  template:
    metadata:
      labels:
        app: cerebral-api
    spec:
      containers:
      - name: cerebral-api
        image: agoraarmbladev.azurecr.io/cerebral-api:0.1
        ports:
        - containerPort: 5003
        env:
        - name: AZURE_OPENAI_API_KEY
          value: "your_azure_openai_api_key"
        - name: CHATGPT_MODEL
          value: "gpt-35-turbo"
        - name: AZURE_OPENAI_ENDPOINT
          value: "your_azure_openai_endpoint"
        - name: OPENAI_API_VERSION
          value: "2024-03-01-preview"
        - name: INFLUXDB_URL
          value: "http://influxdb.cerebral.svc.cluster.local:8086"
        - name: INFLUXDB_BUCKET
          value: "cerebral"
        - name: INFLUXDB_TOKEN
          value: "secret-token"
        - name: INFLUXDB_ORG
          value: "InfluxData"
        - name: REDIS_URL
          value: "redis://redis-service.cerebral.svc.cluster.local:6379"

---
apiVersion: v1
kind: Service
metadata:
  name: cerebral-api-service
  namespace: cerebral
spec:
  type: LoadBalancer
  selector:
    app: cerebral-api
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003